version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra_net
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster

networks:
  cassandra_net:
    driver: bridge
